SELECT *
  , TO_TIMESTAMP_NTZ(TO_CHAR(TM_ID), 'YYYYMMDDHH') AS TM_DATETIME
  , CASE WIND_DIR
    WHEN 0 THEN 'N'
    WHEN 2 THEN 'NNE'
    WHEN 5 THEN 'NE'
    WHEN 7 THEN 'ENE'
    WHEN 9 THEN 'E'
    WHEN 11 THEN 'ESE'
    WHEN 14 THEN 'SE'
    WHEN 16 THEN 'SSE'
    WHEN 18 THEN 'S'
    WHEN 20 THEN 'SSW'
    WHEN 23 THEN 'SW'
    WHEN 25 THEN 'WSW'
    WHEN 27 THEN 'W'
    WHEN 29 THEN 'WNW'
    WHEN 32 THEN 'NW'
    WHEN 34 THEN 'NNW'
    WHEN 36 THEN 'N'
  END AS WIND_DIR_NAME
FROM KMA_DB.ANALYTICS.wind_quarter_daily_vw;