-- SNOWFLAKE 실행환경 준비
USE ROLE ANALYTICS_AUTHOR;
USE WAREHOUSE COMPUTE_WH;

"""
관측지점 및 계절연도 별 계절 시작일 추출 view
용도 : 빅넘버 차트 베이스 데이터
칼럼 : 관측지점 / 계절연도 / 계절라벨 / 시작일(YY-MM-DD)
"""
CREATE OR REPLACE VIEW KMA_DB.ANALYTICS.SEASON_FIRST_DATES_VW AS
SELECT
  STN_KO,
  SEASON_YEAR,
  MAIN_SEASON,
  MIN(TM)::DATE AS FIRST_TM
FROM KMA_DB.RAW_DATA.SEASON_YEARLY
GROUP BY STN_KO, MAIN_SEASON, SEASON_YEAR;
